version: '3.2'
services:
  db:
    image: postgres
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
  web:
    image: circleci-sample
    build:
      context: .
      cache_from:
        - circleci-sample
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/circleci-sample
    ports:
      - "3000:3000"
    environment:
      PGHOST: db
    depends_on:
      - db
