commands:
  echo_command:
    description: echoコマンド
    parameters:
      to:
        default: World
        type: string
    steps:
    - run: echo "Hello, << parameters.to >>"
description: 初めてのOrb
executors:
  default:
    docker:
    - image: busybox
jobs:
  echo_job:
    description: echoジョブ
    executor: default
    parameters:
      to:
        default: World
        type: string
    steps:
    - echo_command:
        to: << parameters.to >>
version: 2.1

