version: 2
jobs:
  build:
    docker:
    - image: circleci/node
    steps:
    - run:
        command: echo Hello Everyone
workflows:
  version: 2
  workflow:
    jobs:
    - build

# Original config.yml file:
# version: 2.1
# commands:
#   # sayhello\u3092\u5B9A\u7FA9
#   sayhello:
#     description: \"Say Hello\"
#     parameters:
#       to:
#         type: string
#         default: \"World\"
#     steps:
#       - run: echo Hello << parameters.to >>
# 
# jobs:
#   build:
#     docker:
#       - image: circleci/node
#     steps:
#       # sayhello\u3092\u5229\u7528
#       - sayhello:
#           # to\u30D1\u30E9\u30E1\u30FC\u30BF\u3092\u4ED8\u4E0E
#           to: Everyone