version: 2.1

jobs:
  release_stage:
    docker:
      - image: busybox
    steps:
      - run: echo "release_stage"

  release_prod:
    docker:
      - image: busybox
    steps:
      - run: echo "release_prod"

workflows:
  version: 2
  stage_prod:
    jobs:
      - release_stage:
          filters:
            branches:
              only: /^stage-.*/
      - release_prod:
          filters:
            branches:
              only:
                - prod
