version: 2.1
jobs:
  build:
    docker:
      - image: circleci/ruby:2.6.5-node-browsers
        environment:
          BUNDLE_JOBS: 3
          BUNDLE_RETRY: 3
          BUNDLE_PATH: vendor/bundle
          PGHOST: localhost
          PGUSER: postgres
          RAILS_ENV: test
      - image: circleci/postgres:9.6.9-alpine
        environment:
          POSTGRES_USER: postgres
          POSTGRES_DB: sample_app_test
          POSTGRES_PASSWORD: ""
    steps:
      - checkout

      - setup_remote_docker

      - restore_cache:
          keys:
            - v2-image-{{ .Branch }}

      - run: |
          set +o pipefail
          docker load -i ~/caches/${CIRCLE_PROJECT_REPONAME}.tar | true

      - run: |
          docker build --cache-from=${CIRCLE_PROJECT_REPONAME} -t ${CIRCLE_PROJECT_REPONAME}:latest .

      - run: |
          docker-compose up -d
          phantomjs screenshot.js

      - run: |
          mkdir -p ~/caches
          docker save -o ~/caches/${CIRCLE_PROJECT_REPONAME}.tar ${CIRCLE_PROJECT_REPONAME}

      - save_cache:
          key: v2-image-{{ .Branch }}
          paths:
            - ~/caches


workflows:
    version: 2
    main:
      jobs:
        - build
