version: 2.1

jobs:
  copy-to-s3:
    docker:
      - image: cimg/python:3.8
    parameters:
      bucket-name:
        description: バケット名
        type: string
        default: my-bucket
    steps:
      - run: aws s3 cp file.txt s3://<< parameters.bucket-name >>/

workflows:
  main:
    jobs:
      - copy-to-s3:
          bucket-name: "123"
