version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node
    steps:
      - run: echo "Hello" > hello.txt
      - run: pwd
      - save_cache:
          paths:
            - ~/project/hello.txt
          key: v1-hello-{{ .Revision }}
  compile:
    docker:
      - image: circleci/node
    steps:
      - run: echo "World" > world.txt
      - save_cache:
          paths:
            - ~/project/world.txt
          key: v1-world-{{ .Revision }}
  deploy:
    docker:
      - image: circleci/node
    steps:
      - restore_cache:
          key: v1-hello-{{ .Revision }}
      - restore_cache:
          key: v1-world-{{ .Revision }}
      - run: cat hello.txt && cat world.txt

workflows:
    version: 2
    main:
      jobs:
        - build
        - compile:
            requires: [build]
        - deploy:
            requires: [compile]
