version: 2.1

orbs:
  cli: circleci/circleci-cli@0.1.5

jobs:
    test:
      executor: cli/default
      steps:
        - cli/install
        - checkout
        - run:
            name: Install yq
            command: |
                sudo apt install jq software-properties-common && \
                sudo add-apt-repository ppa:rmescandon/yq -y && \
                sudo apt update && \
                sudo apt install yq -y
        - run: |
            result=$(circleci config process .circleci/test.yml | yq '.jobs."hello/hello-build".docker[0].image')
            test $result = '"circleci/buildpack-deps:latest"'
            echo $?

workflows:
  main:
    jobs:
      - test

