version: 2.1
jobs:
  install_deps:
    docker:
      - image: circleci/node:12
    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package-lock.json" }}
            - v1-dependencies-

      - run:
          name: 依存関係のインストール
          command: npm install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package-lock.json" }}

      - persist_to_workspace:
          root: ~/project
          paths:
            - build/*
            - node_modules/*

  lint_and_test:
    parameters:
      node-version:
        type: string
        default: "12"
    docker:
      - image: circleci/node:<< parameters.node-version >>
    steps:
      - checkout

      - attach_workspace:
          at: ~/project

      - run:
          name: 静的解析、テスト結果ファイルを出力するディレクトリを作成
          command: mkdir reports

      - run:
          name: コードの静的解析を実行
          command: $(npm bin)/eslint ./src --ext .ts --format junit --output-file ./reports/eslint/eslint.xml

      - run:
          name: テストを実行
          command: $(npm bin)/nyc --silent $(npm bin)/mocha ./test/*.test.ts --require ts-node/register --reporter mocha-junit-reporter
          environment:
            MOCHA_FILE: ./reports/mocha/test-results.xml

      - run:
          name: コードカバレッジを生成
          command: $(npm bin)/nyc report --reporter=lcov

      - store_test_results:
          path: ./reports

      - store_artifacts:
          path: ./reports

      - store_artifacts:
          path: ./coverage
          prefix: coverage

  build:
    parameters:
      node-version:
        type: string
        default: "12"
    docker:
      - image: circleci/node:<< parameters.node-version >>
    steps:
      - checkout

      - attach_workspace:
          at: ~/project

      - run:
          name: TypeScriptコードをビルド
          command: $(npm bin)/tsc

      - when:
          steps:
            - persist_to_workspace:
                root: ./
                paths:
                  - build

  deploy:
    docker:
      - image: circleci/node:12
    steps:
      - attach_workspace:
          at: ./
      - run:
          name: デプロイ
          command: echo "Deployed"
      - store_artifacts:
          path: build

workflows:
  version: 2
  main:
    jobs:
      - install_deps
      - lint_and_test:
          matrix:
            parameters:
              node-version: ["12", "latest"]
          requires:
            - install_deps
      - build:
          matrix:
            parameters:
              node-version: ["12", "latest"]
          requires:
            - lint_and_test
      - deploy:
          requires:
            - build
# https://circleci.com/workflow-run/00259183-1fcb-4e33-9ae7-36599a7d22b1
