version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node
    steps:
      - run: echo "Hello" > hello.txt
      - persist_to_workspace:
            root: ./
            paths:
                - hello.txt
  compile:
    docker:
      - image: circleci/node
    steps:
      - run: echo "World" > world.txt
      - persist_to_workspace:
            root: ./
            paths:
                - world.txt
  deploy:
    docker:
      - image: circleci/node
    steps:
      - attach_workspace:
            at: ./
      - run: cat hello.txt && cat world.txt

workflows:
    version: 2
    main:
      jobs:
        - build
        - compile:
            requires: [build]
        - deploy:
            requires: [compile]
