version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.13.3
      - image: circleci/mysql:5.7
    environment:
      MYSQL_DATABASE: circle_test
      MYSQL_HOST: localhost
      MYSQL_PASS: ""
      MYSQL_USER: root

    working_directory: /go/src/github.com/uraway/circleci-sample

    steps:
      - checkout

      - restore_cache:
          keys:
            - go-module-v2-{{ checksum "go.sum" }}
            - go-module-v2-

      - run: go mod download -json

      - save_cache:
          key: go-module-v2-{{ checksum "go.sum" }}
          paths:
            - /go/pkg/mod

      - run: go get github.com/jstemmer/go-junit-report

      - run: mkdir -p /tmp/test-results/go-test

      - run:
          name: Waiting for DB to be ready
          command: |
            for i in `seq 1 10`;
            do
              nc -z localhost 3306 && echo Success && exit 0
              echo -n .
              sleep 1
            done
            echo Failed waiting for DB && exit 1

      - run: go test -v 2>&1 | go-junit-report > /tmp/test-results/go-test/result.xml

      - store_artifacts:
          path: /tmp/test-results
          destination: raw-test-output

      - store_test_results:
          path: /tmp/test-results
