version: 2
jobs:
  build:
    docker:
      - image: circleci/ruby
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: 環境変数REGISTORY_URLの設定
          command: echo 'export REGISTORY_URL=${DOCKER_USER}/${CIRCLE_PROJECT_REPONAME}' >> $BASH_ENV
      - run:
          name: 指定イメージのpull
          command: docker pull ${REGISTORY_URL}:latest
      - run:
          name: イメージのビルド
          command: docker tag ${REGISTORY_URL}:latest circleci-sample
      - run:
          name: curl
          command: |
            docker run -d -p 3000:3000 --name circleci-sample circleci-sample
            # curl --retry 10 --retry-connrefused http://localhost:3000
            docker exec circleci-sample curl --retry 10 --retry-connrefused http://localhost:3000

workflows:
  version: 2
  main:
    jobs:
    - build
    - e2e:
        requires:
          - build
