version: 2.1

parameters:
  run-integration-tests:
    type: boolean
    default: false

jobs:
  test:
    docker:
      - image: cimg/python:3.7
    steps:
      - run: echo "インテグレーションテスト"

  trigger:
    docker:
      - image: cimg/python:3.7
    steps:
      - run:
          name: integration-testワークフローをトリガする
          command: |
            curl -u ${CIRCLE_TOKEN}: -X POST --header "Content-Type: application/json" -d '{
              "parameters": {
                "run-integration-tests": "true"
              }
            }' https://circleci.com/api/v2/project/<< pipeline.project.type >>/${CIRCLE_PROJECT_USERNAME}/${CIRCLE_PROJECT_REPONAME}/pipeline

workflows:
  integration-test:
    when: << pipeline.parameters.run-integration-tests >> # run-integration-testsがtrueであるときワークフローは実行される
    jobs:
      - test
  trigger-integration-test:
    unless: << pipeline.parameters.run-integration-tests >> # run-integration-testsがfalseであるときワークフローは実行される
    jobs:
      - trigger
