version: 2.1

jobs:
  build:
    docker:
      - image: cimg/node:lts
    steps:
      - setup_remote_docker
      - run:
          name: sample/hello_world.txtファイルの作成
          command: mkdir -p sample && touch sample/hello_world.txt
      - run:
          name: name: docker cpしてリモートDocker環境にフォルダのマウント
          command: |
             docker container create --name tmp -v /sample busybox
             docker cp ./sample/. tmp:/sample
             docker run --volumes-from tmp busybox test -f sample/hello_world.txt

workflows:
  version: 2
  workflow:
    jobs:
      - build
