version: 2.1
jobs:
 build:
   parallelism: 4
   docker:
     - image: busybox
   steps:
     - run: echo "テスト"
     - deploy:
         command: |
          if [ "${CIRCLE_BRANCH}" == "master" ]; then
            echo "デプロイ"
          fi
