version: 2.1
jobs:
  build:
    machine: true
    steps:
      - checkout
      - run: docker run --name phantomjs -d -p 8910:8910 wernight/phantomjs phantomjs
      - run: docker cp ./screenshot.js phantomjs:/screenshot.js
      - run: docker run phantomjs phantomjs screenshot.js
      - run: docker cp phantomjs:/screenshot.png ./
      - store_artifacts:
            path: ./screenshot.png

workflows:
  version: 2
  main:
    jobs:
    - build
