version: 2
# comment
jobs:
# comment
  build:
    # comment
    docker:
      - image: busybox # comment
    steps:
      - run: |
          echo "Hello" # echo "firt comment"
          # echo "second comment"
          echo "World"
