version: 2.1
jobs:
  build:
    docker:
      - image: circleci/python:3.8.1-node
    steps:
      - checkout
      - setup_remote_docker
      - run: |
          docker run --name app mokemokechicken/capture_web "https://circleci.com" screenshot.png
          docker cp app:/tmp/screenshot ./

      - store_artifacts:
            path: ./screenshot

workflows:
    version: 2
    main:
      jobs:
        - build
