version: 2.1

jobs:
  install_deps:
    docker:
      - image: cimg/ruby:2.6.5-node
    steps:
      - run:
          name: Nodeをインストール
          environment:
            NODE_VERSION: 11.10.0
          command: |
            curl -sSL "https://nodejs.org/dist/v${NODE_VERSION}/node-v${NODE_VERSION}-linux-x64.tar.xz" | sudo tar --strip-components=2 -xJ -C /usr/local/bin/ node-v${NODE_VERSION}-linux-x64/bin/node
      - run:
          name: Yarnをインストール
          environment:
            YARN_VERSION: 1.19.1
          command: |
            curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version ${YARN_VERSION}
            echo 'export PATH="$HOME/.yarn/bin:$HOME/.config/yarn/global/node_modules/.bin:$PATH"' >> $BASH_ENV
      - run: node -v # v11.10.0
      - run: yarn -v # 1.19.1

workflows:
  version: 2
  workflow:
    jobs:
      - install_deps # ジョブA

