version: 2.1

orbs:
  cli: circleci/circleci-cli@0.1.5

jobs:
    test:
      machine: true
      steps:
        - cli/install
        - checkout
        - run: circleci config process orb-test.yml > orb-test.2.0.yml
        - run: circleci local execute --config orb-test.2.0.yml --job hello-world/echo_job
workflows:
  main:
    jobs:
      - test
