version: 2.1
jobs:
  build:
    machine: true
    steps:
      - checkout

      - restore_cache:
          keys:
            - v2-image-{{ .Branch }}
            - v2-image-

      - run: |
          docker login -u ${DOCKER_USER} -p ${DOCKER_PASS}

      - run: |
          docker pull ${DOCKER_USER}/${CIRCLE_PROJECT_REPONAME}:latest

      - run: |
          docker build -t ${DOCKER_USER}/${CIRCLE_PROJECT_REPONAME}:latest --cache-from ${DOCKER_USER}/${CIRCLE_PROJECT_REPONAME}:latest .

      - run: |
          docker run ${DOCKER_USER}/${CIRCLE_PROJECT_REPONAME}:latest phantomjs screenshot.js

      # - run: |
      #     docker run -d -p 3000:3000 ${DOCKER_USER}/${CIRCLE_PROJECT_REPONAME}:latest
      #     curl --retry 10 --retry-connrefused http://localhost:3000

      - run: |
          docker push ${DOCKER_USER}/${CIRCLE_PROJECT_REPONAME}:latest

      - store_artifacts:
            path: ./screenshot.png

      - save_cache:
          key: v2-image-{{ .Branch }}
          paths:
            - ~/caches


workflows:
    version: 2
    main:
      jobs:
        - build
