version: 2.1
jobs:
  build:
    machine: true
    steps:
      - checkout
      - run:
          name: イメージのビルド
          command: docker build -t ${CIRCLE_PROJECT_REPONAME} .
      - run:
          name: イメージのレイヤーを.tarにまとめて保存
          command: |
            mkdir -p ~/caches
            docker save -o ~/caches/${CIRCLE_PROJECT_REPONAME}.tar ${CIRCLE_PROJECT_REPONAME}

      - persist_to_workspace:
            root: ~/
            paths:
                - caches

  e2e:
    machine: true
    steps:
        - checkout
        - attach_workspace:
              at: ~/
        - run: docker images

        - run:
            name: イメージの.tarキャッシュがあればロード
            command: |
              set +o pipefail
              docker load -i ~/caches/${CIRCLE_PROJECT_REPONAME}.tar | true

        - run: docker images
        - run: docker run ${CIRCLE_PROJECT_REPONAME} phantomjs screenshot.js

workflows:
  version: 2
  main:
    jobs:
    - build
    - e2e:
        requires:
          - build
