version: 2
jobs:
  build:
    machine: true
    steps:
      - checkout
      - run: docker login -u ${DOCKER_USER} -p ${DOCKER_PASS}
      - run: echo 'export REGISTORY_URL=${DOCKER_USER}/${CIRCLE_PROJECT_REPONAME}' >> $BASH_ENV
      - run: docker pull ${REGISTORY_URL}:latest
      - run: docker build -t ${REGISTORY_URL}:latest --cache-from ${REGISTORY_URL}:latest .
      - run: docker push ${REGISTORY_URL}:latest

workflows:
  version: 2
  main:
    jobs:
    - build
