version: 2.1

jobs:
  build:
    parameters:
      ruby-version:
        type: string
      db-image:
        type: string
    docker:
      - image: circleci/ruby:<< parameters.ruby-version >>
      - image: circleci/<< parameters.db-image >>
    steps:
      - run: echo 'build job'

  deploy:
    machine: true
    steps:
      - run: echo 'deploy job'

workflows:
  version: 2
  workflow:
    jobs:
      - build:
          name: build-<< matrix.ruby-version >>-on-<< matrix.db-image >>
          matrix:
            parameters:
              ruby-version: ["2.5", "2.6", "2.7"]
              db-image: [mysql, postgres]
            exclude:
              - ruby-version: "2.5"
                db-image: mysql
      - deploy:
          requires:
            - build
