version: 2.1

orbs:
  win: circleci/windows@2.4.0

jobs:
  build:
    executor: win/default
    steps:
      - run:
         command: Write-Host 'Hello, World!
         shell: powershell.exe
      - run:
         command: echo 'Hello, World!
         shell: bash.exe
      - run:
         command: echo 'Hello, World!
         shell: cmd.exe
