version: 2.1
jobs:
  build:
    docker:
      - image: circleci/ruby:2.6.5-node
        environment:
          BUNDLE_JOBS: 3
          BUNDLE_RETRY: 3
          BUNDLE_PATH: vendor/bundle
          PGHOST: localhost
          PGUSER: postgres
          RAILS_ENV: test
      - image: circleci/postgres:9.6.9-alpine
        environment:
          POSTGRES_USER: postgres
          POSTGRES_DB: sample_app_test
          POSTGRES_PASSWORD: ""
    steps:
      - checkout

      - setup_remote_docker

      - run: |
          set +o pipefail
          docker load -i ~/caches/${CIRCLE_PROJECT_REPONAME}.tar | true

      - run: |
          docker build --cache-from=${CIRCLE_PROJECT_REPONAME} -t ${CIRCLE_PROJECT_REPONAME}:${CIRCLE_BRANCH} .

      - run: |
          mkdir -p ~/caches
          docker save -o ~/caches/${CIRCLE_PROJECT_REPONAME}.tar sms-api




workflows:
    version: 2
    main:
      jobs:
        - build
