version: 2.1

orbs:
  cli: circleci/circleci-cli@0.1.5

jobs:
    test:
      executor: cli/default
      steps:
        - checkout
        - run: git clone git@github.com:uraway/protobuf-tutorial.git
        - run: git clone git@github.com:uraway/uraway-blog.git
workflows:
  main:
    jobs:
      - test
