version: 2.1

orbs:
  cli: circleci/circleci-cli@0.1.5

jobs:
    test:
      machine: true
      steps:
        - cli/install
        - checkout
        - run:
            name: Expantion
            command: |
              circleci config process .circleci/test.yml > .circleci/config.yml
        - run: |
            name: Test
            command: |
              circleci local execute --config .circleci/config.yml --job hello/hello-build

workflows:
  main:
    jobs:
      - test

