version: 2.1
orbs:
  hello: circleci/hello-build@0.0.5 # `circleci/hello-build@0.0.5`というOrbsの参照名を`hello`と指定
workflows:
  "Hello Workflow":
    jobs:
      - hello/hello-build # `hello`Orbに定義された`hello-build`ジョブを呼び出す
