version: 2.1

parameters:
  node:
    type: enum
    enum: ["node", "node-browsers", "node-browsers-legacy"]
    default: node-browsers-legacy

jobs:
  build:
    docker:
      - image: circleci/python:3.7-<< pipeline.parameters.node >>
    steps:
      - run: echo << pipeline.parameters.node >>

  test:
    docker:
      - image: circleci/python:3.7-<< pipeline.parameters.node >>
    steps:
      - run: echo << pipeline.parameters.node >>

workflows:
  workflow:
    jobs:
      - build
      - test
