version: 2
jobs:
  build:
    docker:
      - image: circleci/ruby
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: tmpディレクトリの作成
          command: mkdir -p tmp
      - run:
          name: フォルダのマウント
          command: docker run -v tmp:/tmp busybox ls

workflows:
  version: 2
  main:
    jobs:
    - build
    - e2e:
        requires:
          - build
