version: 2
jobs:
 build:
   parallelism: 4
   docker:
     - image: circleci/node:latest
   steps:
     - run: mkdir -p ./coverage
     - run: echo "テスト" > ./coverage/hello.txt
     - store_artifacts:
         path: ./coverage
         destination: coverage
