version: 2.1

parameters:
  run-deploy:
    type: boolean
    default: true

jobs:
  deploy_job:
    machine: true
    steps:
      - checkout
      - when:
          condition:
            or:
              - << pipeline.parameters.run-deploy >>
              - equal: [ master, << pipeline.git.branch >> ]
          steps:
            - run: echo "deploy"

workflows:
  version: 2
  main:
    jobs:
      - deploy_job
