version: 2.1

orbs:
  win: circleci/windows@2.4.0

jobs:
  build:
    executor: win/default
    steps:
      - checkout
      - run:
          command: ver
          shell: cmd.exe
      - run:
          command: Get-Date
          shell: powershell.exe
      - run:
          command: echo 'This is bash'
          shell: bash.exe

workflows:
  version: 2
  workflow:
    jobs:
      - build