version: 2.1
jobs:
  build_and_push:
    docker:
      - image: circleci/ruby:2.6.5-node
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Docker Hubへログイン
          command: docker login -u ${DOCKER_USER} -p ${DOCKER_PASS}
      - run:
          name: 環境変数REGISTORY_URLの設定
          command: echo 'export REGISTORY_URL=${DOCKER_USER}/${CIRCLE_PROJECT_REPONAME}' >> $BASH_ENV
      - run:
          name: 指定イメージのpull
          command: docker pull ${REGISTORY_URL}:latest
      - run: docker images
      - run:
          name: イメージのビルド
          command: docker build -t ${REGISTORY_URL} --cache-from ${REGISTORY_URL}:latest .
      - run:
          name: ビルドしたイメージはそのままpushが可能
          command: docker push ${REGISTORY_URL}

workflows:
    version: 2
    main:
      jobs:
        - build_and_push
