version: 2

jobs:
  build:
    docker:
      - image: busybox
    steps:
      - run:
          echo 'Hello World' >> README.md
          cat README.md

workflows:
  version: 2
  "Hello Workflow":
    jobs:
      - build
