version: 2.1
jobs:
  build:
    machine: true
    steps:
      - checkout
      - run: |
          docker container create --name tmp -v /tmp-volume busybox
          docker cp ./screenshot.js tmp:/app/screenshot.js
          docker run --volumes-from tmp circleci/ruby:2.6.5-browsers-legacy phantomjs screenshot.js

      - store_artifacts:
            path: ./screenshot.png

workflows:
    version: 2
    main:
      jobs:
        - build
