version: 2.1

orbs:
  cli: circleci/circleci-cli@0.1.5

jobs:
    test:
      machine: true
      steps:
        - cli/install
        - checkout
        - run: mkdir -p tmp-config-src
        - run: cp .circleci/test.yml config.yml
        - run:
            command: circleci local execute -c config.yml | tee local_build_output.txt /dev/stderr | tail -n 1 | grep "Success"
            name: run test job locally

workflows:
  main:
    jobs:
      - test

