version: 2.1
commands:
  run-tests:
    parameters:
      your-test:
        type: steps
        default: []
    steps:
    - run: mkdir -p ./test-results
    - steps: << parameters.your-test >>
    - store_test_results:
        path: ./test-results

jobs:
  build:
    docker:
      - image: cimg/ruby:2.7
    steps:
    - run-tests:
        your-test:
          - run: bundle exec rubocop
          - run: bundle exec rspec
