version: 2
jobs:
  build:
    machine: true
    steps:
      - checkout
      - when:
          condition:
            - not:
              - equal: [ development, $CIRCLE_BRANCH ]
          steps:
            - run: echo "deploy"

workflows:
  main:
    jobs:
      - build
