version: 2

jobs:
    install_deps:
        docker:
            - image: alpine
        steps:
            - run: echo "Install Deps"
    test_1:
        docker:
            - image: alpine
        steps:
            - run: echo "test_1" > foo.bin
            - run: apk add --no-cache ca-certificates
            - save_cache:
                  paths:
                    -  foo.bin
                  key: foo.bin-{{ .Revision }}
    test_2:
        docker:
            - image: alpine
        steps:
            - run: echo "test_2" > foo.bin
            - run: apk add --no-cache ca-certificates
            - save_cache:
                  paths:
                    -  foo.bin
                  key: foo.bin-{{ .Revision }}
    deploy:
        docker:
            - image: alpine
        steps:
            - restore_cache:
                key: foo.bin-{{ .Revision }}
            - run: cat foo.bin

workflows:
  version: 2
  workflow:
    jobs:
      - install_deps # ... ジョブA
      - test_1:      # ... ジョブB
          requires:
            - install_deps
      - test_2:      # ... ジョブC
          requires:
            - install_deps
      - deploy:      # ... ジョブD
          requires:
            - test_1
            - test_2
