version: 2.1

parameters:
  run-deploy:
    type: boolean
    default: false

jobs:
  test:
    machine: true
    steps:
      - checkout

  build:
    machine: true
    steps:
      - checkout

  deploy:
    machine: true
    steps:
      - checkout



