version: 2.1

orbs:
  cli: circleci/circleci-cli@0.1.5

jobs:
    test:
      executor: cli/default
      steps:
        - cli/install
        - checkout
        - run: |
            result=$(circleci config process .circleci/test.yml | yq '.jobs."hello/hello-build".docker[0].image')
            test $result = '"circleci/buildpack-deps:latest"'
            echo $?

workflows:
  main:
    jobs:
      - test

