version: 2.1
description: # The purpose of this orb

orbs:
  cli: circleci/circleci-cli@0.1.5

jobs:
    test:
      executor: cli/default
      steps:
        - cli/install
        - checkout
        - run: circleci orb validate ./src/orb.yml

workflows:
  main:
    jobs:
      - test
