version: 2.1
jobs:
  build:
    machine: true
    steps:
      - checkout
      - run: |
          docker run --name app --rm -v $PWD:/srv lifenz/docker-screenshot https://circleci.com screenshot.png 1920px 2000 1
          docker cp app:/srv ./

      - store_artifacts:
            path: ./screenshot

workflows:
    version: 2
    main:
      jobs:
        - build
