version: 2
jobs:
  build:
    docker:
      - image: circleci/ruby
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: sampleディレクトリの作成
          command: mkdir -p sample && touch sample/hello_world.txt
      - run:
          name: 確認
          command: |
            test -f sample/hello_world.txt;
      - run:
          name: busyboxイメージのpull
          command: docker pull busybox
      - run:
          name: フォルダのマウント
          command: |
            docker container create --name tmp -v /sample busybox
            docker cp ./sample tmp:/sample
            docker run --volumes-from tmp busybox test -f sample/hello_world.txt

workflows:
  version: 2
  main:
    jobs:
    - build
