version: 2.1
jobs:
  build:
    docker:
      - image: circleci/ruby:2.6.5-node
        environment:
          BUNDLE_JOBS: 3
          BUNDLE_RETRY: 3
          BUNDLE_PATH: vendor/bundle
          PGHOST: localhost
          PGUSER: postgres
          RAILS_ENV: test
      - image: circleci/postgres:9.6.9-alpine
        environment:
          POSTGRES_USER: postgres
          POSTGRES_DB: sample_app_test
          POSTGRES_PASSWORD: ""
    steps:
      - checkout

      - setup_remote_docker

      - restore_cache:
          keys:
            - rails-bundle-v1-{{ checksum "Gemfile.lock" }}
            - rails-bundle-v1-

      - run: bundle install

      - run: |
          CONTAINER_NAME=sample-container

          docker build -t myapp:$CIRCLE_BRANCH .
          docker run --name $CONTAINER_NAME -d -p 80:80 myapp:$CIRCLE_BRANCH
          docker exec -it $CONTAINER_NAME ls

          docker cp ./ $CONTAINER_NAME:circleci-sample/
          docker exec -it $CONTAINER_NAME ls

      - save_cache:
          key: rails-bundle-v1-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle


workflows:
    version: 2
    main:
      jobs:
        - build
