version: 2.1

jobs:
  deploy:
    docker:
      - image: busybox
    steps:
      - checkout
      - deploy:
          command: echo "deploy"

workflows:
  version: 2
  workflow:
    jobs:
      - deploy
