version: 2
jobs:
  build:
    docker:
      - image: circleci/ruby
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: sampleディレクトリの作成
          command: mkdir -p sample && touch sample/hello_world.txt
      - run:
          name: 確認
          command: |
            test -f sample/hello_world.txt; echo $?
      - run:
          name: busyboxイメージのpull
          command: docker pull busybox
      - run:
          name: フォルダのマウント
          command: |
            docker run -v sample:/sample busybox test -f sample/hello_world.txt; echo $?

workflows:
  version: 2
  main:
    jobs:
    - build
