version: 2
jobs:
  build:
    machine: true
    steps:
    - checkout
    - run: docker login -u ${DOCKER_USER} -p ${DOCKER_PASS}
    - run: docker pull ${DOCKER_USER}/${CIRCLE_PROJECT_REPONAME}:latest
    - run: docker images
    - run: docker build -t ${DOCKER_USER}/${CIRCLE_PROJECT_REPONAME}:latest --cache-from ${DOCKER_USER}/${CIRCLE_PROJECT_REPONAME}:latest .
    - run: docker run ${DOCKER_USER}/${CIRCLE_PROJECT_REPONAME}:latest phantomjs screenshot.js
    - run: docker push ${DOCKER_USER}/${CIRCLE_PROJECT_REPONAME}:latest
    - store_artifacts:
        path: ./screenshot.png

workflows:
  version: 2
  main:
    jobs:
    - build
