version: 2.1
jobs:
  build:
    machine: true
    steps:
      - checkout
      - run: |
          docker run --name app mokemokechicken/capture_web "https://circleci.com" screenshot.png
          docker cp app:/tmp/screenshot ./

      - store_artifacts:
            path: ./screenshot

workflows:
    version: 2
    main:
      jobs:
        - build
