version: 2.1

parameters:
  run-integration-tests:
    type: boolean
    default: false

jobs:
  test:
    docker:
      - image: circleci/python:3.7
    steps:
      - run: echo "インテグレーションテスト"

  trigger:
    docker:
      - image: circleci/python:3.7
    steps:
      - run:
          name: integration-testワークフローをトリガする
          command: |
            echo << pipeline.project.type >>

            curl -u ${CIRCLE_TOKEN}: -X POST --header "Content-Type: application/json" -d "{
              \"parameters\": {\"run-integration-tests\": true\"}
            }" "https://circleci.com/api/v2/project/<< pipeline.project.type >>/${CIRCLE_PROJECT_USERNAME}/${CIRCLE_PROJECT_REPONAME}/pipeline"

workflows:
  integration-test:
    when: << pipeline.parameters.run-integration-tests >>
    jobs:
      - test
  trigger-integration-test:
    unless: << pipeline.parameters.run-integration-tests >>
    jobs:
      - trigger
