version: 2.1
jobs:
  build:
    machine: true
    steps:
      - checkout

      - run: |
          docker build -t ${CIRCLE_PROJECT_REPONAME}:latest .

      - run: |
          docker run ${CIRCLE_PROJECT_REPONAME}:latest phantomjs screenshot.js

      - store_artifacts:
            path: ./screenshot.png

workflows:
    version: 2
    main:
      jobs:
        - build
