version: 2.1

jobs:
  build:
    docker:
      - image: cimg/node:lts
    steps:
      - setup_remote_docker
      - run:
          name: sample/hello_world.txtファイルの作成
          command: mkdir -p sample && touch sample/hello_world.txt
      - run: # ステップ1：このステップは成功する
          name: プライマリコンテナで確認
          command: |
            test -f sample/hello_world.txt
      - run: # ステップ2：このステップは失敗する
          name: リモートDocker環境にフォルダのマウントを行って確認
          command: |
            docker run -v sample:/sample busybox test -f sample/hello_world.txt

workflows:
  version: 2
  workflow:
    jobs:
      - build
