version: 2.1

orbs:
  cli: circleci/circleci-cli@0.1.5

jobs:
    test:
      executor: cli/default
      steps:
        - cli/install
        - checkout
        - run:
            name: Install yq
            command: |
              sudo apt update && \
              sudo apt-get install jq python-pip python-dev && \
              sudo pip install yq
        - run:
            name: Test
            command: |
              expected='echo "Hello, CircleCI"'
              result=$(circleci config process .circleci/test.yml | yq '.jobs."hello-world/echo_job".steps[0].run.command')
              test "${result}" = "${expected}";
              echo $?;

workflows:
  main:
    jobs:
      - test
