version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.13.3
      - image: circleci/mysql:5.7

    working_directory: /go/src/github.com/uraway/circleci-sample

    steps:
      - checkout

      - restore_cache:
          keys:
            - go-module-v2-{{ checksum "go.sum" }}
            - go-module-v2-

      - run:
          name: Download modules
          command: |
            go mod download -json

      - save_cache:
          key: go-module-v2-{{ checksum "go.sum" }}
          paths:
            - /go/pkg/mod

      - run:
          name: Create tmp dir
          command: |
            mkdir -p /tmp/test-results/go-test
            mkdir -p /tmp/test-results/golangci-lint

      - run:
          name: Run golangci-lint
          command: |
            curl -sfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh| sh -s v1.21.0
            ./bin/golangci-lint run --out-format junit-xml > /tmp/test-results/golangci-lint/result.xml

      - run:
          name: Waiting for DB to be ready
          command: |
            for i in `seq 1 10`;
            do
              nc -z localhost 3306 && echo Success && exit 0
              echo -n .
              sleep 1
            done
            echo Failed waiting for DB && exit 1

      - run:
          name: Prepare for test
          command: |
            go get github.com/jstemmer/go-junit-report

      - run:
          name: Run go test
          environment:
            DATABSE_URL: "root@localhost:3306/circle_test"
            GIN_MODE: test
          command: |
            go test
            go test -v 2>&1 | go-junit-report > /tmp/test-results/go-test/result.xml

      - store_artifacts:
          path: /tmp/test-results
          destination: raw-test-output

      - store_test_results:
          path: /tmp/test-results
