version: 2.1

jobs:
  eslint:
    docker:
      - image: cimg/node:lts
    parameters:
      cache:
        description: キャッシュ
        type: boolean
        default: false
    steps:
      - run: yarn eslint <<# parameters.cache >> --cache <</ parameters.cache >>

workflows:
  main:
    jobs:
      - eslint:
          cache: true
