version: 2.1

orbs:
  cli: circleci/circleci-cli@0.1.5

jobs:
    test:
      docker:
        - image: circleci/python
      steps:
        - setup_remote_docker
        - cli/install
        - checkout
        - run: circleci local execute --config .circleci/processed.yml --job hello-world/echo_job | tee local_build_output.txt /dev/stderr | tail -n 1 | grep "Success"

workflows:
  main:
    jobs:
      - test
