version: 2.1

jobs:
  proofreading_job:
    docker:
      - image: circleci/node
    environment:
      REVIEWDOG_VERSION: 0.9.13
    steps:
      - checkout
      - run:
          name: "依存モジュールをインストールする"
          command: npm install
      - run:
          name: "reviewdogをインストールする"
          command: |
            curl -sfL https://raw.githubusercontent.com/reviewdog/reviewdog/master/install.sh| sh -s  v$REVIEWDOG_VERSION
      - run:
          name: "textlintをREADME.mdに対して実行する"
          command: $(npm bin)/textlint -f checkstyle README.md >> .textlint.log
      - run:
          name: "reviewdogを実行する"
          when: on_fail
          command: |
            export REVIEWDOG_GITHUB_API_TOKEN=${GITHUB_TOKEN}
            cat .textlint.log | ./bin/reviewdog -f=checkstyle -name="textlint" -reporter="github-pr-review"

workflows:
  version: 2
  proofreading:
    jobs:
      - proofreading_job
