version: 2.1
jobs:
  build:
    docker:
      - image: busybox
    steps:
      - run: circleci version
      - run: circleci step halt
      - run: circleci version

workflows:
  version: 2
  main:
    jobs:
    - build
