version: 2
jobs:
  build:
    machine: true
    steps:
      - checkout
      - run: docker login -u ${DOCKER_USER} -p ${DOCKER_PASS}
      - run:
          name: 環境変数REGISTORY_URLの設定
          command: echo 'export REGISTORY_URL=${DOCKER_USER}/${CIRCLE_PROJECT_REPONAME}' >> $BASH_ENV
      - run:
          name: 指定イメージのpull
          command: docker pull ${REGISTORY_URL}:latest
      - run:
          name: イメージのビルド
          command: docker build -t sample-app --cache-from ${REGISTORY_URL}:latest .
      - run: docker push ${REGISTORY_URL}:latest

      - run:
          name: イメージのレイヤーを.tarにまとめて保存
          command: |
            mkdir -p ~/caches
            docker save -o ~/caches/${CIRCLE_PROJECT_REPONAME}.tar ${REGISTORY_URL}

      - persist_to_workspace:
            root: ~/
            paths:
                - caches

  e2e:
    machine: true
    steps:
        - checkout
        - attach_workspace:
              at: ~/
        - setup_remote_docker
        - run: docker images

        - run:
            name: イメージの.tarキャッシュがあればロード
            command: |
              set +o pipefail
              docker load -i ~/caches/${CIRCLE_PROJECT_REPONAME}.tar | true

        - run: docker images
        - run: docker run ${CIRCLE_PROJECT_REPONAME} phantomjs screenshot.js

workflows:
  version: 2
  main:
    jobs:
    - build
    - e2e:
        requires:
          - build
