version: 2.1
jobs:
  build:
    machine: true
    steps:
      - when:
          condition:
            or:
              - not:
                - equal: [ development, dd ]
              - and: [ $CIRCLE_TAG ]
          steps:
            - run: echo "deploy"
