version: 2.1

executors:
  python:
    docker:
      - image: cimg/python:3.6.11
  with_db:
    docker:
      - image: cimg/python:3.6.11
      - image: circleci/postgres:9.6.2

jobs:
  test:
    parameters:
      e:
        type: executor
    executor: << parameters.e >>
    steps:
      - run: echo << parameters.e >>

workflows:
  workflow:
    jobs:
      - test:
          e: python
      - test:
          e: with_db
