version: 2.1

orbs:
  cli: circleci/circleci-cli@0.1.5
  orb-tools: circleci/orb-tools@8.27.4

jobs:
    test:
      executor: orb-tools/alpine
      steps:
        - run:
            name: Dockerクライアントのインストール
            command:
              VER="17.03.0-ce"
              curl -L -o /tmp/docker-$VER.tgz https://download.docker.com/linux/static/stable/x86_64/docker-$VER.tgz
              tar -xz -C /tmp -f /tmp/docker-$VER.tgz
              mv /tmp/docker/* /usr/bin
        - setup_remote_docker
        - run: which docker
        - cli/install
        - checkout
        - run: pwd
        #- run: circleci config process .circleci/test.yml > config.yml
        - orb-tools/local-test-build:
            test-config-location: .circleci/test.yml
        #- run: circleci local execute --config config.yml --job hello-world/echo_job | tee local_build_output.txt /dev/stderr | tail -n 1 | grep "Success"

workflows:
  main:
    jobs:
      - test
