version: 2.1
jobs:
  test:
   parallelism: 4
   docker:
     - image: busybox
   steps:
     - run: echo "テスト"
  deploy:
   docker:
     - image: busybox
   steps:
     - run: echo "デプロイ"

workflows:
  version: 2
  test_deploy:
    jobs:
      - test
      - deploy:
          filters:
            branches:
              only:
               - master
          requires:
            - test
