version: 2.1

orbs:
  cli: circleci/circleci-cli@0.1.5

jobs:
    test:
      executor: cli/default
      steps:
        - setup_remote_docker
        - cli/install
        - checkout
        - run: pwd
        - run: circleci local execute --volume /home/circleci/project:/home/circleci/project --config /home/circleci/project/.circleci/processed.yml --job hello-world/echo_job | tee local_build_output.txt /dev/stderr | tail -n 1 | grep "Success"

workflows:
  main:
    jobs:
      - test
