version: 2
jobs:
  build:
    docker:
        - image: busybox
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: 環境変数REGISTORY_URLの設定
          command: echo 'export REGISTORY_URL=${DOCKER_USER}/${CIRCLE_PROJECT_REPONAME}' >> $BASH_ENV
      - run:
          name: 指定イメージのpull
          command: docker pull ${REGISTORY_URL}:latest
      - run:
          name: イメージのビルド
          command: docker build -t circleci-sample --cache-from ${REGISTORY_URL}:latest .
      - run:
          name: curl
          command: |
            docker run -d -p 3000:3000 circleci-sample
            curl --retry 10 --retry-connrefused http://localhost:3000

workflows:
  version: 2
  main:
    jobs:
    - build
    - e2e:
        requires:
          - build
