version: 2.1
jobs:
  build:
    docker:
      - image: circleci/ruby:2.7.1
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: docker cpしてリモートDocker環境にフォルダのマウント
          command: |
            docker container create --name tmp -v /sample busybox
            docker cp ./sample/. tmp:/sample
            docker run --volumes-from tmp busybox test -f sample/hello_world.txt

workflows:
  version: 2
  main:
    jobs:
      - build
