version: 2.1

orbs:
  cli: circleci/circleci-cli@0.1.5
  orb-tools: circleci/orb-tools@8.27.4

jobs:
    test:
      docker:
        - image: circleci/python
      steps:
        - setup_remote_docker
        - cli/install
        - checkout
        - run: pwd
        - run: circleci config process .circleci/test.yml > config.yml
        - orb-toos/local-test-build:
            test-config-location: ./config.yml
        - run: circleci local execute --config config.yml --job hello-world/echo_job | tee local_build_output.txt /dev/stderr | tail -n 1 | grep "Success"

workflows:
  main:
    jobs:
      - test
