orbs:
  orb-tools: circleci/orb-tools@8.27.4

version: 2.1
workflows:
  publish-orb:
    jobs:
      - orb-tools/publish-dev:
          name: publish-orb-dev
          orb-path: ./src/orb.yml
          orb-name: uraway/hello-build
          checkout: true
          validate: true
      - orb-tools/trigger-integration-workflow:
          filters:
            branches:
              only: master
          requires: [publish-orb-dev]
          tag: master
