version: 2.1
jobs:
  build:
    docker:
      - image: alpine
    steps:
      - run: apk add curl
      - run: which docker | true
      - setup_remote_docker
      - run: which docker | true
      - run:
          name: Install Docker client
          command: |
            set -x
            VER="17.03.0-ce"
            curl -L -o /tmp/docker-$VER.tgz https://download.docker.com/linux/static/stable/x86_64/docker-$VER.tgz
            tar -xz -C /tmp -f /tmp/docker-$VER.tgz
            mv /tmp/docker/* /usr/bin

      - run: which docker | true

workflows:
  version: 2
  main:
    jobs:
    - build
