version: 2

jobs:
    install_deps:
        docker:
            - image: busybox
        steps:
            - run: echo "Install Deps"
    test_1:
        docker:
            - image: busybox
        steps:
            - run: echo "test_1" > foo.bin
            - run: ls -al
            - run: apk add ca-certificates
            - persist_to_workspace:
                root: ./
                paths:
                  - "foo.bin"
    test_2:
        docker:
            - image: busybox
        steps:
            - run: echo "test_2" > foo.bin
            - run: ls -al
            - run: apk add ca-certificates
            - persist_to_workspace:
                root: ./
                paths:
                  - "foo.bin"
    deploy:
        docker:
            - image: busybox
        steps:
            - attach_workspace:
                  at: ./
            - run: echo "Install Deps"

workflows:
  version: 2
  workflow:
    jobs:
      - install_deps # ... ジョブA
      - test_1:      # ... ジョブB
          requires:
            - install_deps
      - test_2:      # ... ジョブC
          requires:
            - install_deps
      - deploy:      # ... ジョブD
          requires:
            - test_1
            - test_2
