version: 2.1
jobs:
  build_and_test:
    parallelism: 3
    docker:
      - image: circleci/ruby:2.6.5-node
        environment:
          BUNDLE_JOBS: 3
          BUNDLE_RETRY: 3
          BUNDLE_PATH: vendor/bundle
          PGHOST: localhost
          PGUSER: postgres
          RAILS_ENV: test
      - image: circleci/postgres:9.6.9-alpine
        environment:
          POSTGRES_USER: postgres
          POSTGRES_DB: sample_app_test
          POSTGRES_PASSWORD: ""
    steps:
      - checkout

      - setup_remote_docker:
          docker_layer_caching: true

      - run: docker build -t myapp:$CIRCLE_BRANCH .

      - run: docker images

workflows:
    version: 2
    main:
      jobs:
        - build
