version: 2.1
jobs:
  build:
    machine: true
    steps:
      - checkout
      - run: |
          docker run -v `pwd`:/tmp/screenshot mokemokechicken/capture_web "https://circleci.com" screenshot.png

      - store_artifacts:
            path: ./screenshot

workflows:
    version: 2
    main:
      jobs:
        - build
