version: 2.1
jobs:
  build:
    docker:
      - image: circleci/ruby:2.7.1
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: sample/hello_world.txtファイルの作成
          command: mkdir -p sample && touch sample/hello_world.txt
      - run: # ステップ1：このステップは成功する
          name: プライマリコンテナで確認
          command: |
            test -f sample/hello_world.txt

  build2:
    docker:
      - image: circleci/ruby:2.7.1
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: sample/hello_world.txtファイルの作成
          command: mkdir -p sample && touch sample/hello_world.txt
      - run: # ステップ2：このステップは失敗する
          name: リモートDocker環境にフォルダのマウントを行って確認
          command: |
            docker run -v sample:/sample busybox test -f sample/hello_world.txt

workflows:
  version: 2
  main:
    jobs:
      - build
      - build2
