version: 2.1

jobs:
  install_deps:
    machine: true
    steps:
      - run: echo "install_deps" >> foo.bin
      - persist_to_workspace:
          root: .
          paths:
            - foo.bin

  test_1:
    machine: true
    steps:
      - run: echo "test_1" >> foo.bin
      - persist_to_workspace:
          root: .
          paths:
            - foo.bin

  test_2:
    machine: true
    steps:
      - attach_workspace:
          at: .
      - run: cat foo.bin

  deploy:
    machine: true
    steps:
      - attach_workspace:
          at: .
      - run: cat foo.bin

workflows:
  version: 2
  workflow:
    jobs:
      - install_deps # ジョブA
      - test_1:      # ジョブB
          requires:
            - install_deps
      - test_2:      # ジョブC
          requires:
            - install_deps
      - deploy:      # ジョブD
          requires:
            - test_1
            - test_2

