version: 2
jobs:
  build:
    docker:
      - image: circleci/ruby
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: sampleディレクトリの作成
          command: mkdir -p sample && touch sample/hello_world.txt
      - run:
          name: 確認
          command: |
            result = $(ls sample)
            if ["${result}" == "hello_world.txt"]; then
              echo "success"
            fi
      - run:
          name: busyboxイメージのpull
          command: docker pull busybox
      - run:
          name: フォルダのマウント
          command: |
            result = $(docker run -v sample:/sample busybox ls sample)
            if ["${result}" == "hello_world.txt"]; then
              echo "success"
            fi

workflows:
  version: 2
  main:
    jobs:
    - build
