version: 2.1

jobs:
  build:
    machine: true
    steps:
      - run: mkdir -p /tmp/dir/ && touch /tmp/dir/foo
      - run: echo "hello world" >> /tmp/dir/foo
      - persist_to_workspace:
          root: /tmp/dir
          paths:
            - foo

  deploy:
    machine: true
    steps:
      - attach_workspace:
          at: ./
      - run: cat foo
      - run: cat /tmp/dir/foo

workflows:
  main:
    jobs:
      - build
      - deploy:
          requires:
            - build

