version: 2.1

jobs:
  build:
    parameters:
      parallelism:
        type: integer
        default: 1
    parallelism: << parameters.parallelism >>
    machine: true
    steps:
      - checkout

workflows:
  workflow:
    jobs:
      - build:
          parallelism: 2
