version: 2
jobs:
 test_deploy:
   parallelism: 4
   docker:
     - image: busybox
   steps:
     - run: echo "テスト"
     - deploy: |
          if [ "${CIRCLE_BRANCH}" == "master" ]; then
            echo "デプロイ"
          fi
