version: 2

jobs:
    test:
      machine: true
      steps:
        - checkout
        - add_ssh_keys:
              fingerprints:
                  - 00:53:70:ec:a7:60:5c:c1:c5:9d:a2:36:eb:00:99:70
        - run: |
            git config --global user.email "circleci@example.com"
            git config --global user.name "CircleCI"
        - run:
            name: 新しいdev用Orbを使って、別リポジトリのビルドを開始する
            command: |
              export TEST_REPOSITORY=hello-world-integration-test
              export BRANCH="INTEGRATION_TEST/${CIRCLE_SHA1}"

              git clone git@github.com:uraway/${TEST_REPOSITORY}.git
              cd hello-world-integration-test
              git checkout -b ${BRANCH}
              mkdir -p .circleci
              cat <<EOF > .circleci/config.yml
                version: 2.1
                orbs:
                  hello-world: uraway/hello-world@dev:volatile
                workflows:
                  hello-workflow:
                    jobs:
                      - hello-world/echo_job:
                          to: CircleCI
              EOF
              git add .
              git commit -m "Updates from ${CIRCLE_BUILD_URL}"
              git push -f --set-upstream origin ${BRANCH}

        - run:
            name: ビルドが成功するまで問い合わせる
            command: |
              while true; do
                curl https://circleci.com/api/v1.1/project/github/uraway/${TEST_REPOSITORY}/tree/${BRANCH}?limit=1 > build-result.json
                cat build-result.json
                LIFECYCLE=$(cat build-result.json | jq -r '.[0].lifecycle')
                if [ "$LIFECYCLE" == "finished" ];then
                  STATUS=$(cat build-result.json | jq -r '.[0].status')
                  if [ "$STATUS" == "success" ];then
                    echo "Success"
                    exit 0
                  else
                    exit 1
                  fi
                else
                  sleep 20
                fi
              done
workflows:
  version: 2
  main:
    jobs:
      - test
