version: 2.1

orbs:
  cli: circleci/circleci-cli@0.1.5
  orb-tools: circleci/orb-tools@8.27.4

jobs:
    test:
      executor: orb-tools/ubuntu
      steps:
        - run:
            name: Dockerクライアントのインストール
            command:
              apt-get update
              apt-get install docker-ce docker-ce-cli containerd.io
        - setup_remote_docker
        - run: which docker
        - cli/install
        - checkout
        - run: pwd
        #- run: circleci config process .circleci/test.yml > config.yml
        - orb-tools/local-test-build:
            test-config-location: .circleci/test.yml
        #- run: circleci local execute --config config.yml --job hello-world/echo_job | tee local_build_output.txt /dev/stderr | tail -n 1 | grep "Success"

workflows:
  main:
    jobs:
      - test
