version: 2.1

orbs:
  cli: circleci/circleci-cli@0.1.5

jobs:
    test:
      machine: true
      steps:
        - cli/install
        - checkout
        - run: circleci config process .circleci/test.yml >> .circleci/2.0.yml
        - run: circleci local execute --config .circleci/2.0.yml --job hello/hello-build | tee local_build_output.txt /dev/stderr | tail -n 1 | grep "Success"

workflows:
  main:
    jobs:
      - test

