version: 2.1

jobs:
  build:
    docker:
      - image: busybox

    steps:
      - run: echo build

  deploy:
    docker:
      - image: busybox

    steps:
      - run: echo deploy

workflows:
  version: 2
  build-test-and-approval-deploy:
    jobs:
      - build
      - hold:
          type: approval
          requires:
            - build
      - deploy:
          requires:
            - hold
