version: 2.1
jobs:
  build:
    machine: true
    steps:
      - checkout
      - when:
          condition:
            or:
              - not:
                - equal: [ development, $CIRCLE_BRANCH ]
              - and: [ $CIRCLE_TAG ]
          steps:
            - run: echo "deploy"
            - run: echo $CIRCLE_TAG
