version: 2.1

orbs:
  cli: circleci/circleci-cli@0.1.5

jobs:
    test:
      executor: cli/default
      steps:
        - cli/install
        - checkout
        - setup_remote_docker
        - run:
            name: Expantion
            command: |
              circleci config process .circleci/test.yml > .circleci/config.yml
        - run: |
            name: Test
            command: |
              circleci local execute --job hello/hello-build

workflows:
  main:
    jobs:
      - test

