version: 2.1

executors:
  default:
    parameters:
      tag:
        type: string
        default: "curl-browsers"
    docker:
      - image: circleci/buildpack-deps:<< parameters.tag >>

jobs:
  hello-build:
    executor: default
    steps:
      - run: echo "Hello, build!"
