version: 2.1

description: "初めてのOrb"

executors:
  default:
    docker:
      - image: busybox

jobs:
  echo_job:
    description: "echoジョブ"
    parameters:
      to:
        type: string
        default: "World"
    executor: default
    steps:
      - echo_command:
          to: << parameters.to >>

commands:
  echo_command:
    description: "echoコマンド"
    parameters:
      to:
        type: string
        default: "World"
    steps:
      - run: echo "Hello, << parameters.to >>"
