version: 2.1

executors:
  default:
    parameters:
      tag:
        type: string
        default: "latest"
    docker:
      - image: circleci/buildpack-deps:<< parameters.tag >>

jobs:
  hello-build:
    parameters:
      e:
        type: executor
    executor: << parameters.e >>
    steps:
      - run: echo "Hello, build!"
